[workspace]

members = [
    "client-cli", 
    "client-gui",
    "client-core",
    "client-transit",
    "libsocks",
    "libtransit",
    "server-monolith",
    "libsecrets"
]

workspace.resolver = "2"
