[workspace]

members = [
    "client-cli", 
    "client-gui",
    "client-core",
    "libsocks",
    "libtransit",
    "server-monolith",
    "server",
    "libsecrets",
    "integration-tests"
]

workspace.resolver = "2"
