[workspace]

members = [
    "client-cli", 
    "client-core",
    "libsocks",
    "libtransit",
    "server-monolith",
    "libsecrets",
    "integration-tests",
    "hypertunnel_gui"
]

workspace.resolver = "2"
